# Cloudflare Pages Functions配置

# 绑定D1数据库
[[d1_databases]]
binding = "CONTACT_DB" # 在代码中使用context.env.CONTACT_DB访问
database_name = "screenview_contacts" # 在Cloudflare Dashboard中创建的数据库名称
database_id = "" # 这个ID需要从Dashboard获取 